### ISSUE TITLE
cannot load own script

### ISSUE THREAD

**Issue by rolfschumacher** [GeertBellekens/Enterprise-Architect-VBScript-Library#9]
imported all your scripts
did an own one in a new project browser group, added the path and the group lines on top
stored all scripts successfully to filesystem using SaveAllScripts
tried to load them in a different model but failed when it comes to the new group:
at line 121 I get the failure message: "Object doesn't support this property or method: 'newScript.GroupType'"

**Comment by rolfschumacher** [comment]
I commented out the calls to that procedure at line 81 and 110 as well as line 91. Now it seems to work. However, what did I miss?

**Comment by baerrach** [comment]
![image](https://user-images.githubusercontent.com/723962/220787823-2cbf7cb4-e5ef-4514-b624-3bffe3f3a76e.png)
